/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FFgotPass extends javax.swing.JFrame {

    /**
     * Creates new form FFgotPass
     */
    public FFgotPass() {
        initComponents();
        this.setSize(new java.awt.Dimension(1040, 735));
        generatedRandomQuestion();
    }
    
    private int num1, num2, answer;
    private boolean securityQuestionAnswered = false;

    private void generatedRandomQuestion() {
        Random random = new Random();
        num1 = random.nextInt(10) + 1; // Angka pertama antara 1 dan 10
        num2 = random.nextInt(10) + 1; // Angka kedua antara 1 dan 10
        answer = num1 * num2;

        lblSoal.setText("Berapa hasil dari " + num1 + " x " + num2 + "?");
    }
    
        private boolean checkAnswer(int userAnswer) {
        boolean isCorrect = userAnswer == answer;
        if (isCorrect) {
            securityQuestionAnswered = true;
            JOptionPane.showMessageDialog(this, "Jawaban benar. Anda dapat memperbarui password.");
        } else {
            JOptionPane.showMessageDialog(this, "Jawaban salah. Coba lagi!");
        }
        return isCorrect;
    }
        
            private void updatePassword() {

        if (securityQuestionAnswered) {
                // Implementasi pembaruan password di sini, sesuai dengan logika database Anda
                // Ambil username, nim, dan password baru dari field teks
            String Email = txtEmail.getText();
            String nim = txtNim.getText();
            String newPassword = txtNewPass.getText();
            try {
                String sql = "UPDATE user SET password = ? WHERE Email = ? AND nim = ?";
                Connection conn = Config.configDB();
    
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, newPassword);
                    pstmt.setString(2, Email);
                    pstmt.setString(3, nim);

                    int affectedRows = pstmt.executeUpdate();

                    if (affectedRows > 0) {
                        JOptionPane.showMessageDialog(this, "Password berhasil diperbarui!\nSilahkan Login Kembali");
                        FLogin login = new FLogin(); //pindah frame ke login
                        login.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal memperbarui password. Periksa kredensial Anda.");
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui password.");
}
        } else {
            JOptionPane.showMessageDialog(this, "Jawab pertanyaan keamanan terlebih dahulu!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        f = new javax.swing.JLabel();
        txtJawaban = new javax.swing.JTextField();
        txtNewPass = new javax.swing.JTextField();
        lblSoal = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ìmage/logo-poliban1(1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Politeknik Negeri Banjarmasin");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 703, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1040, 91);

        jPanel1.setBackground(new java.awt.Color(57, 144, 161));
        jPanel1.setLayout(null);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setText("Email");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(310, 200, 408, 56);

        txtNim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNim.setText("NIM");
        txtNim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNimFocusLost(evt);
            }
        });
        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });
        jPanel1.add(txtNim);
        txtNim.setBounds(310, 260, 408, 56);

        f.setBackground(new java.awt.Color(255, 255, 255));
        f.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setText("Forgot Password");
        jPanel1.add(f);
        f.setBounds(360, 40, 290, 48);

        txtJawaban.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtJawaban.setText("Jawaban");
        txtJawaban.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJawabanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJawabanFocusLost(evt);
            }
        });
        jPanel1.add(txtJawaban);
        txtJawaban.setBounds(310, 320, 410, 54);

        txtNewPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNewPass.setText("New Password");
        txtNewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPassFocusLost(evt);
            }
        });
        jPanel1.add(txtNewPass);
        txtNewPass.setBounds(310, 380, 408, 58);

        lblSoal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(lblSoal);
        lblSoal.setBounds(320, 130, 390, 50);

        btnSubmit.setBackground(new java.awt.Color(0, 153, 255));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(400, 500, 230, 60);

        jPanel3.setBackground(new java.awt.Color(57, 144, 161));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ìmage/back.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(57, 144, 161));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kembali");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 560, 150, 61);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 72, 1040, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try {
            int userAnswer = Integer.parseInt(txtJawaban.getText());
            if (checkAnswer(userAnswer)) {
                updatePassword();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan jawaban dalam bentuk angka!");
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if (txtEmail.getText().equals("Email")) {
        txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if (txtEmail.getText().equals("")) {
        txtEmail.setText("Email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtNimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNimFocusGained
        // TODO add your handling code here:
        if (txtNim.getText().equals("NIM")) {
        txtNim.setText("");
        }
    }//GEN-LAST:event_txtNimFocusGained

    private void txtNimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNimFocusLost
        // TODO add your handling code here:
        if (txtNim.getText().equals("")) {
        txtNim.setText("NIM");
        }
    }//GEN-LAST:event_txtNimFocusLost

    private void txtJawabanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJawabanFocusGained
        // TODO add your handling code here:
        if (txtJawaban.getText().equals("Jawaban")) {
        txtJawaban.setText("");
        }
    }//GEN-LAST:event_txtJawabanFocusGained

    private void txtJawabanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJawabanFocusLost
        // TODO add your handling code here:
        if (txtJawaban.getText().equals("")) {
        txtJawaban.setText("Jawaban");
        }
    }//GEN-LAST:event_txtJawabanFocusLost

    private void txtNewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPassFocusGained
        // TODO add your handling code here:
        if (txtNewPass.getText().equals("New Password")) {
        txtNewPass.setText("");
        }
    }//GEN-LAST:event_txtNewPassFocusGained

    private void txtNewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPassFocusLost
        // TODO add your handling code here:
        if (txtNewPass.getText().equals("")) {
        txtNewPass.setText("New Password");
        }
    }//GEN-LAST:event_txtNewPassFocusLost

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        FLogin back = new FLogin();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FFgotPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FFgotPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FFgotPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FFgotPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FFgotPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblSoal;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtJawaban;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
